# Generated by Django 4.0.5 on 2022-06-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='carmodel',
            table='cars1',
        ),
    ]
