# Generated by Django 4.0.5 on 2022-06-29 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_carmodel_price_alter_carmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='carmodel',
            table='cars',
        ),
    ]
