# Generated by Django 4.0.5 on 2022-07-01 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carmodel_options_carmodel_create_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={},
        ),
    ]
